eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: order-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/springcloud-sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

mybatis:
  type-aliases-package: com.dmcq.order.domain.entity
  mapper-locations: classpath:mapper/*.xml
  mappers: com.dmcq.order.common.mapper.MyBaseMapper
  not-empty: false
  identity: MYSQL

server:
  port: 9003


logging:
  path: log
  file: myFirstLog.log
  level: info

PRODUCT-SERVER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

