eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost
#    ip-address: 106.13.117.203
#    hostname: ${spring.cloud.client.ipAddress}
  client:
    service-url:
      defaultZone: http://eureka1:8100/eureka/,http://eureka2:8200/eureka/

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qinpiyi/config-repo.git
          basedir: /app/git/github/config-repo
#          basedir: D:\workspaces\git\github\config-repo
#          username: dmcq-qpy
#          password: dmcq123456
  rabbitmq:
    host: 106.13.117.203
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8101